// Copyright (c) 2016, 2018, Oracle and/or its affiliates. All rights reserved.
// Code generated. DO NOT EDIT.

// Event Control Service API
//
// API for managing event rules and actions.
// For more information, see Overview of Events (https://docs.us-phoenix-1.oraclecloud.com/iaas/Content/Events/Concepts/eventsoverview.htm).
//

package cloudevents

import (
	"encoding/json"
	"github.com/oracle/oci-go-sdk/common"
)

// NoOpAction An action for testing rules.
type NoOpAction struct {

	// The OCID (https://docs.us-phoenix-1.oraclecloud.com/iaas/Content/General/Concepts/identifiers.htm) of the action.
	Id *string `mandatory:"true" json:"id"`

	// A message generated by the Events service about the current state of this rule.
	LifecycleMessage *string `mandatory:"true" json:"lifecycleMessage"`

	// This string is meant for internal testing.
	DisplayName *string `mandatory:"false" json:"displayName"`

	// The current state of the rule.
	LifecycleState ActionLifecycleStateEnum `mandatory:"true" json:"lifecycleState"`
}

//GetId returns Id
func (m NoOpAction) GetId() *string {
	return m.Id
}

//GetLifecycleMessage returns LifecycleMessage
func (m NoOpAction) GetLifecycleMessage() *string {
	return m.LifecycleMessage
}

//GetLifecycleState returns LifecycleState
func (m NoOpAction) GetLifecycleState() ActionLifecycleStateEnum {
	return m.LifecycleState
}

func (m NoOpAction) String() string {
	return common.PointerString(m)
}

// MarshalJSON marshals to json representation
func (m NoOpAction) MarshalJSON() (buff []byte, e error) {
	type MarshalTypeNoOpAction NoOpAction
	s := struct {
		DiscriminatorParam string `json:"actionType"`
		MarshalTypeNoOpAction
	}{
		"NOOP",
		(MarshalTypeNoOpAction)(m),
	}

	return json.Marshal(&s)
}
