// Copyright (c) 2016, 2018, Oracle and/or its affiliates. All rights reserved.
// Code generated. DO NOT EDIT.

// Event Control Service API
//
// API for managing event rules and actions.
// For more information, see Overview of Events (https://docs.us-phoenix-1.oraclecloud.com/iaas/Content/Events/Concepts/eventsoverview.htm).
//

package cloudevents

import (
	"encoding/json"
	"github.com/oracle/oci-go-sdk/common"
)

// ObjectStorageServiceAction An action that delivers to an Oracle Object Storage bucket.
type ObjectStorageServiceAction struct {

	// The OCID (https://docs.us-phoenix-1.oraclecloud.com/iaas/Content/General/Concepts/identifiers.htm) of the action.
	Id *string `mandatory:"true" json:"id"`

	// A message generated by the Events service about the current state of this rule.
	LifecycleMessage *string `mandatory:"true" json:"lifecycleMessage"`

	// The Object Storage namespace in which the bucket lives.
	NamespaceName *string `mandatory:"false" json:"namespaceName"`

	// The name of the bucket.
	// Example: `my-new-bucket1`
	BucketName *string `mandatory:"false" json:"bucketName"`

	// The current state of the rule.
	LifecycleState ActionLifecycleStateEnum `mandatory:"true" json:"lifecycleState"`
}

//GetId returns Id
func (m ObjectStorageServiceAction) GetId() *string {
	return m.Id
}

//GetLifecycleMessage returns LifecycleMessage
func (m ObjectStorageServiceAction) GetLifecycleMessage() *string {
	return m.LifecycleMessage
}

//GetLifecycleState returns LifecycleState
func (m ObjectStorageServiceAction) GetLifecycleState() ActionLifecycleStateEnum {
	return m.LifecycleState
}

func (m ObjectStorageServiceAction) String() string {
	return common.PointerString(m)
}

// MarshalJSON marshals to json representation
func (m ObjectStorageServiceAction) MarshalJSON() (buff []byte, e error) {
	type MarshalTypeObjectStorageServiceAction ObjectStorageServiceAction
	s := struct {
		DiscriminatorParam string `json:"actionType"`
		MarshalTypeObjectStorageServiceAction
	}{
		"OBJECTSTORAGE",
		(MarshalTypeObjectStorageServiceAction)(m),
	}

	return json.Marshal(&s)
}
